name: Build and push docker image

on:
  push:
    branches:
      - main 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Docker build 
      run: |
        docker build -t netflix_frontend:latest .

